# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJC4AuLYyPRj29KfgaSM2xmr2fTpVG2P
"""

# Prompt Engineering Implementation
### Zero-shot, Few-shot, CoT, Interview, Tree of Thoughts

# This notebook implements and compares:
# - Zero-shot Prompting
# - Few-shot Prompting
# - Chain of Thought (CoT)
# - Interview Prompting
# - Tree of Thoughts (ToT)

problem = """
A shopkeeper buys a pen for ₹10 and sells it for ₹15.
He sells 20 pens. What is the profit?
"""
print(problem)

def zero_shot(problem):
    return "Profit per pen = 15 - 10 = 5. Total profit = 5 × 20 = ₹100"

print("Zero-shot Output:")
print(zero_shot(problem))

def few_shot(problem):
    examples = """
Example 1:
CP = 20, SP = 30, Quantity = 10
Profit = (30-20)*10 = 100

Example 2:
CP = 50, SP = 70, Quantity = 5
Profit = (70-50)*5 = 100
"""
    answer = "Using pattern: (15-10)*20 = ₹100"
    return examples + "\nAnswer:\n" + answer

print("Few-shot Output:")
print(few_shot(problem))

def chain_of_thought(problem):
    return """
Step 1: Cost Price = 10
Step 2: Selling Price = 15
Step 3: Profit per pen = 15 - 10 = 5
Step 4: Total profit = 5 × 20 = ₹100
Final Answer: ₹100
"""

print("Chain of Thought Output:")
print(chain_of_thought(problem))

def interview_prompting(problem):
    return """
Q1: What is the cost price per pen? → 10
Q2: What is the selling price per pen? → 15
Q3: What is profit per pen? → 5
Q4: What is profit for 20 pens? → 5 × 20 = ₹100
"""

print("Interview Prompting Output:")
print(interview_prompting(problem))

def tree_of_thought(problem):
    return """
Approach 1: Profit method
Profit per pen = 15 - 10 = 5
Total profit = 5 × 20 = ₹100

Approach 2: Revenue - Cost
Revenue = 15 × 20 = 300
Cost = 10 × 20 = 200
Profit = 300 - 200 = ₹100

Conclusion: Both methods give ₹100
"""

print("Tree of Thoughts Output:")
print(tree_of_thought(problem))

import pandas as pd

data = {
    "Method": ["Zero-shot", "Few-shot", "Chain of Thought", "Interview", "Tree of Thoughts"],
    "Reasoning Strength": ["Low", "Medium", "High", "Very High", "Extremely High"],
    "Accuracy": ["Medium", "High", "Very High", "Very High", "Best"],
    "Use Case": [
        "Simple Q&A",
        "Pattern tasks",
        "Math/Logic",
        "Teaching systems",
        "AI Agents"
    ]
}

df = pd.DataFrame(data)
df

comparison = {
    "Aspect": ["Examples given?", "Performance", "Cost", "Best for"],
    "Zero-shot": ["No", "Medium", "Low", "Simple tasks"],
    "Few-shot": ["Yes", "High", "Medium", "Pattern problems"]
}

pd.DataFrame(comparison)

#chain of thoughts
!pip install transformers

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "Solve step by step: A pen costs 10, sells 15, sold 20. Profit?"
output = generator(prompt, max_length=100)

print(output[0]["generated_text"])

