# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123cXVt5hS4VKBalR_EzK8XIyg0ZP9TwB
"""

import numpy as np
from scipy.stats import multivariate_normal

class GMM:
    def __init__(self, k=2, iterations=100):
        self.k = k
        self.iterations = iterations

    def fit(self, X):
        n, d = X.shape

        # Initialize
        self.means = X[np.random.choice(n, self.k, replace=False)]
        self.covariances = [np.eye(d) for _ in range(self.k)]
        self.weights = np.ones(self.k) / self.k

        for _ in range(self.iterations):
            # E-step
            responsibilities = np.zeros((n, self.k))

            for i in range(self.k):
                responsibilities[:, i] = self.weights[i] * \
                    multivariate_normal(self.means[i], self.covariances[i]).pdf(X)

            responsibilities /= responsibilities.sum(axis=1, keepdims=True)

            # M-step
            Nk = responsibilities.sum(axis=0)

            for i in range(self.k):
                self.means[i] = (X.T @ responsibilities[:, i]) / Nk[i]

                diff = X - self.means[i]
                self.covariances[i] = (responsibilities[:, i][:, None] * diff).T @ diff / Nk[i]

                self.weights[i] = Nk[i] / n

    def sample(self, n_samples=5):
        samples = []
        for _ in range(n_samples):
            component = np.random.choice(self.k, p=self.weights)
            sample = np.random.multivariate_normal(self.means[component], self.covariances[component])
            samples.append(sample)
        return np.array(samples)

X = np.random.randn(200, 2)
gmm = GMM(k=2)
gmm.fit(X)

print(gmm.sample(5))

