# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXRINLVNuYt4tUt6x0NeJGFq35Z8EeAk
"""

pip install torch torchvision transformers pillow

import torch
from PIL import Image
from transformers import CLIPProcessor, CLIPModel

# Load pretrained CLIP model
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

# Load image
image = Image.open("/content/cat.jpg")

# Candidate captions
captions = [
    "a dog running in the park",
    "a cat sitting on a chair",
    "a person riding a bicycle",
    "a group of people walking",
    "a beautiful landscape with mountains"
]

# Process image and text
inputs = processor(text=captions, images=image, return_tensors="pt", padding=True)

# Model prediction
outputs = model(**inputs)

logits_per_image = outputs.logits_per_image
probs = logits_per_image.softmax(dim=1)

# Get best caption
best_caption = captions[probs.argmax()]

print("Predicted Caption:", best_caption)

